2022-05-27 17:01:30 — housing.core.pipelines.task_runner — ERROR — run_task:78 — Failed to complete task : task-6e346cc2-bfa8-4a22-a93a-1233feb1d989 : Unexpected Error
Traceback (most recent call last):
  File "/mnt/c/Users/shreya.kanodia/Documents/TIGER_ASSIGNMNETS/MODULE_6/module6.2/regression-py/src/housing/core/pipelines/task_runner.py", line 70, in run_task
    processor(context, task_params)
  File "/mnt/c/Users/shreya.kanodia/Documents/TIGER_ASSIGNMNETS/MODULE_6/module6.2/regression-py/src/housing/core/pipelines/processors.py", line 42, in _wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/shreya.kanodia/Documents/TIGER_ASSIGNMNETS/MODULE_6/module6.2/regression-py/production/data_cleaning.py", line 45, in clean_housing_table
    imputer.fit(housing_df)
  File "/home/shreyakanodia/miniconda3/envs/env-housing_price-dev/lib/python3.8/site-packages/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/shreyakanodia/miniconda3/envs/env-housing_price-dev/lib/python3.8/site-packages/sklearn/impute/_base.py", line 249, in _validate_input
    raise new_ve from None
ValueError: Cannot use median strategy with non-numeric data:
could not convert string to float: 'NEAR BAY'
2022-05-27 17:01:30 — housing.core.pipelines.task_runner — ERROR — run_task:78 — Failed to complete task : task-418b0c02-47f1-4094-86d9-3d29fa1841aa : Unexpected Error
Traceback (most recent call last):
  File "/mnt/c/Users/shreya.kanodia/Documents/TIGER_ASSIGNMNETS/MODULE_6/module6.2/regression-py/src/housing/core/pipelines/task_runner.py", line 70, in run_task
    processor(context, task_params)
  File "/mnt/c/Users/shreya.kanodia/Documents/TIGER_ASSIGNMNETS/MODULE_6/module6.2/regression-py/src/housing/core/pipelines/processors.py", line 42, in _wrapper
    return func(*args, **kwargs)
  File "/mnt/c/Users/shreya.kanodia/Documents/TIGER_ASSIGNMNETS/MODULE_6/module6.2/regression-py/production/data_cleaning.py", line 70, in create_training_datasets
    housing_df_processed = load_dataset(context, input_dataset)
  File "/mnt/c/Users/shreya.kanodia/Documents/TIGER_ASSIGNMNETS/MODULE_6/module6.2/regression-py/src/housing/core/dataset.py", line 90, in load_dataset
    df = utils.load_data(data_uri[0], fs=fs, **load_params)
IndexError: list index out of range
